### ISSUE TITLE
The subscribed button does not turn gray

### ISSUE THREAD

**Issue by sapondanaisriwan** [DamienDavisNeff/RedSubscribeButton#11]
If you move to another language, the subscribed button does not turn gray. If you use English, it works perfectly.

https://www.youtube.com/@MuseThailand/channels
https://www.youtube.com/feed/guide_builder

https://user-images.githubusercontent.com/64634605/222971342-cc732320-c29a-499f-9924-207c3cef6ffe.mp4

**Comment by sapondanaisriwan** [comment]
I just had a look and it's just the `[aria-label]` that changes. It's time to write a long selector and include other languages.

**Comment by DamienDavisNeff** [comment]
Thank you for bringing this to my attention, for now I'll add the selectors for the top languages used on YouTube, and slowly add the rest over time.

**Comment by DamienDavisNeff** [comment]
I was able to solve this without adding a long selector. Instead of checking the aria-label, this was achieved by checking if the div containing the notification icons were hidden or not. 

`ytd-subscribe-button-renderer:has(> #notification-preference-toggle-button[hidden]) > yt-button-shape > button`

**Comment by sapondanaisriwan** [comment]
It's not working if you are on Firefox because the `:has` pseudo-class is still not supported, but you may enable it by setting the Experimental Web Platform features flag. In my opinion it's not proper for average users.

![Can I use :has?](https://user-images.githubusercontent.com/64634605/223623963-8a7c11c1-7082-4c51-b39f-83daa5c7aab1.png)

**Comment by sapondanaisriwan** [comment]
You can try using `@supports not (:has()) {}` and making some kind of an alert pseudo-element to notify users something won't work unless they enable that config option.

**Comment by DamienDavisNeff** [comment]
At some point I caused this to reappear.

**Comment by DamienDavisNeff** [comment]
For now I am reimplementing the original solution and finding a different workaround.

**Comment by sapondanaisriwan** [comment]
Here is my solution that I just used in my [project](https://github.com/sapondanaisriwan/AdashimaaTube)
```
/* Removes notification icon */
#notification-preference-button[hidden],

/* Removes subscribed btn */
tp-yt-paper-button.ytd-subscribe-button-renderer[subscribed] {
    display: none !important;
}

/* Remove modern subscribe btn */
yt-button-shape.ytd-subscribe-button-renderer {
    display: none;
}

/* Display the old subscribe btn */
tp-yt-paper-button.ytd-subscribe-button-renderer {
    display: block !important;
    border-radius: 18px;
}
```

**Comment by sapondanaisriwan** [comment]
@DamienDavisNeff I hope you understand what I say (sorry for my bad English lol)

**Comment by DamienDavisNeff** [comment]
It's alright, I believe I do understand and I appreciate the help on this one. I'll look more into this later, to see if I can get something similar working.

**Comment by DamienDavisNeff** [comment]
Since this is just a issue on Firefox, which [I no longer plan on supporting](https://github.com/DamienDavisNeff/RedSubscribeButton/issues/20), this issue will be marked as resolved unless somehow it re-pops up in chromium browsers.
