### ISSUE TITLE
The main buttons hidden

### ISSUE THREAD

**Issue by Jamesgsburns** [DamienDavisNeff/RedSubscribeButton#15]
![image](https://user-images.githubusercontent.com/121324756/224762876-c7877011-39ad-4840-acf8-150c85007c65.png)

**Comment by Jamesgsburns** [comment]
The "analysis" button is there on your own videos but the "edit video" one is hidden. The subscribe and join buttons are hidden on channels and channel search results as well.

**Comment by DamienDavisNeff** [comment]
If you don't mind letting me know, what browser & version of the extension are you using?

**Comment by DamienDavisNeff** [comment]
After a bit of investigating, this seems to be caused by the same issue as #16. A temporary workaround is opening the popup menu for the settings, while I work on a fix.

**Comment by DamienDavisNeff** [comment]
After even further investigation, this specific problem only seems to impact the currently live version, and not the upcoming v0.5.0.1 update, and so I believe this is fixed. It will be a little while before it goes live, but as I said, the current workaround is to open the settings menu once, and then it should fix the problem. 

Of course the underlying issue also causes #16 on all browsers, and so I will try to fix this as soon as possible.

**Comment by DamienDavisNeff** [comment]
@Jamesgsburns, this will be fixed very shortly on Firefox, but may take a while to go through the staging process on chromium based browsers, including edge. For now, make sure to use the workaround above to ensure the best experience. 

Thank you for the feedback!

**Comment by DamienDavisNeff** [comment]
Thanks for letting me know this was a problem on Chrome as well. The fix is being rolled out and should be published in the next few days 🤞

The current workaround, if you haven't used it already, is opening the popup menu, which should apply the settings. @Jamesgsburns
